sudo: required
services:
  - docker
  
before install:
  - docker build -t PremkumarVasudevan/docker-prem -f Dockerfile.dev .

script:
  - docker run PremkumarVasudevan/docker-prem npm run test -- --coverage

